# Generated by Django 5.2.1 on 2025-05-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motionalert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='alerts/'),
        ),
    ]
